### ISSUE TITLE
Exception when trying to "branch"

### ISSUE THREAD

**Issue by captain-mingo** [tonyblatt/git-guru#14]
Exception in thread "main" java.lang.NullPointerException
        at git_guru.commands$get_pass_BANG_.invoke(commands.clj:24)
        at git_guru.commands$get_uname_and_pass_BANG_.invoke(commands.clj:33)
        at git_guru.commands$pull_BANG_.invoke(commands.clj:81)
        at git_guru.branching$do_branch_BANG_.invoke(branching.clj:21)
        at git_guru.core$branch_BANG_.invoke(core.clj:27)
        at git_guru.core$_main.doInvoke(core.clj:49)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at git_guru.core.main(Unknown Source)

**Comment by tonyblatt** [comment]
this should now be fixed...
